name: GUIShop
main: com.pablo67340.guishop.Main
version: 7.3.7
author: pablo67340
description: Shop Plugin for any server.
depend: [Vault]
api-version: 1.13
permissions:
    guishop.use:
        default: false
        description: Grants access to GUIShop
    guishop.shop.*:
        default: false
        description: Grants access to specific items in shop
    guishop.reload:
        default: false
        description: Grants access to reload shops
    guishop.creator:
        default: false
        description: Grants access to GUIShop Creator